language: python
sudo: false
cache:
  directories:
    - buildout-cache
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py --setuptools-version=8.3 -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coverage==3.6 coveralls
  - coveralls
notifications:
  irc:
    - "irc.freenode.org#plomino"
